import { Poppins } from "next/font/google";
import "./globals.css";
import Header from './components/Header';
import Footer from './components/Footer';

const myFont = Poppins({
  subsets: ['latin', 'latin-ext'],
  weight: '400',
  variable: '--poppins-font'
});

export const metadata = {
  title: "Male&FemaleFashion",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${myFont.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}